/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2018-2021, The Linux Foundation. All rights reserved.
 * Copyright (c) 2022-2023, Qualcomm Innovation Center, Inc. All rights reserved.
 */

#ifndef __CVP_HFI_IO_H__
#define __CVP_HFI_IO_H__

#include <linux/io.h>
#define EVA_LSR
#define CVP_TOP_BASE_OFFS			0x00000000
#define CVP_SS_IDLE_STATUS		(CVP_TOP_BASE_OFFS + 0x50)

#define CVP_CPU_BASE_OFFS			0x000A0000
#define CVP_AON_BASE_OFFS			0x000E0000

#define CVP_CPU_CS_A2HSOFTINTEN		(CVP_CPU_BASE_OFFS + 0x10)
#define CVP_CPU_CS_A2HSOFTINTENCLR	(CVP_CPU_BASE_OFFS + 0x14)
#define CVP_CPU_CS_A2HSOFTINT		(CVP_CPU_BASE_OFFS + 0x18)
#define CVP_CPU_CS_A2HSOFTINTCLR	(CVP_CPU_BASE_OFFS + 0x1C)
#define CVP_CPU_CS_VMIMSG		(CVP_CPU_BASE_OFFS + 0x34)
#define CVP_CPU_CS_VMIMSGAG0		(CVP_CPU_BASE_OFFS + 0x38)
#define CVP_CPU_CS_VMIMSGAG1		(CVP_CPU_BASE_OFFS + 0x3C)
#define CVP_CPU_CS_VMIMSGAG2		(CVP_CPU_BASE_OFFS + 0x40)
#define CVP_CPU_CS_VMIMSGAG3		(CVP_CPU_BASE_OFFS + 0x44)
#define CVP_CPU_CS_SCIACMD			(CVP_CPU_BASE_OFFS + 0x48)
#define CVP_CPU_CS_AXI4_QOS		(CVP_CPU_BASE_OFFS + 0x13C)
#define CVP_CPU_CS_H2XSOFTINTEN		(CVP_CPU_BASE_OFFS + 0x148)

/* CVP_CTRL_STATUS */
#define CVP_CPU_CS_SCIACMDARG0		(CVP_CPU_BASE_OFFS + 0x4C)
#define CVP_CPU_CS_SCIACMDARG0_BMSK	0xff
#define CVP_CPU_CS_SCIACMDARG0_SHFT	0x0
#define CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_ERROR_STATUS_BMSK	0xfe
#define CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_ERROR_STATUS_SHFT	0x1
#define CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_STATUS_BMSK	0x1
#define CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_STATUS_SHFT	0x0
#define CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_PC_READY           0x100

/* HFI_QTBL_INFO */
#define CVP_CPU_CS_SCIACMDARG1		(CVP_CPU_BASE_OFFS + 0x50)

/* HFI_QTBL_ADDR */
#define CVP_CPU_CS_SCIACMDARG2		(CVP_CPU_BASE_OFFS + 0x54)

/* HFI_VERSION_INFO */
#define CVP_CPU_CS_SCIACMDARG3		(CVP_CPU_BASE_OFFS + 0x58)

/* CVP_SFR_ADDR */
#define CVP_CPU_CS_SCIBCMD		(CVP_CPU_BASE_OFFS + 0x5C)

/* CVP_MMAP_ADDR */
#define CVP_CPU_CS_SCIBCMDARG0		(CVP_CPU_BASE_OFFS + 0x60)

/* CVP_UC_REGION_ADDR */
#define CVP_CPU_CS_SCIBARG1		(CVP_CPU_BASE_OFFS + 0x64)

/* CVP_UC_REGION_ADDR */
#define CVP_CPU_CS_SCIBARG2		(CVP_CPU_BASE_OFFS + 0x68)

#define CVP_CPU_CS_SCIBARG3		(CVP_CPU_BASE_OFFS + 0x6C)

#define CVP_CPU_CS_H2ASOFTINTEN		(CVP_CPU_BASE_OFFS + 0x148)
#define CVP_CPU_CS_H2ASOFTINTENCLR	(CVP_CPU_BASE_OFFS + 0x14c)
#define CVP_CPU_CS_H2ASOFTINT		(CVP_CPU_BASE_OFFS + 0x150)
#define CVP_CPU_CS_H2ASOFTINTCLR	(CVP_CPU_BASE_OFFS + 0x154)

#define CVP_AHB_BRIDGE_SYNC_RESET	(CVP_CPU_BASE_OFFS + 0x160)

/* FAL10 Feature Control */
#define CVP_CPU_CS_X2RPMh		(CVP_CPU_BASE_OFFS + 0x168)
#define CVP_CPU_CS_X2RPMh_MASK0_BMSK	0x1
#define CVP_CPU_CS_X2RPMh_MASK0_SHFT	0x0
#define CVP_CPU_CS_X2RPMh_MASK1_BMSK	0x2
#define CVP_CPU_CS_X2RPMh_MASK1_SHFT	0x1
#define CVP_CPU_CS_X2RPMh_SWOVERRIDE_BMSK	0x4
#define CVP_CPU_CS_X2RPMh_SWOVERRIDE_SHFT	0x3

/*
 * --------------------------------------------------------------------------
 * MODULE: cvp_wrapper
 * --------------------------------------------------------------------------
 */
#define CVP_WRAPPER_BASE_OFFS		0x000B0000

#define CVP_WRAPPER_HW_VERSION		(CVP_WRAPPER_BASE_OFFS + 0x00)
#define CVP_WRAPPER_HW_VERSION_MAJOR_VERSION_MASK  0x78000000
#define CVP_WRAPPER_HW_VERSION_MAJOR_VERSION_SHIFT 28
#define CVP_WRAPPER_HW_VERSION_MINOR_VERSION_MASK  0xFFF0000
#define CVP_WRAPPER_HW_VERSION_MINOR_VERSION_SHIFT 16
#define CVP_WRAPPER_HW_VERSION_STEP_VERSION_MASK   0xFFFF

#define CVP_WRAPPER_INTR_STATUS	(CVP_WRAPPER_BASE_OFFS + 0x0C)
#define CVP_WRAPPER_INTR_STATUS_A2HWD_BMSK	0x8
#define CVP_WRAPPER_INTR_STATUS_A2H_BMSK	0x4

#define CVP_SS_IRQ_MASK    (CVP_TOP_BASE_OFFS + 0x04)
#define CVP_SS_INTR_BMASK  (0x100)

#define CVP_WRAPPER_INTR_MASK		(CVP_WRAPPER_BASE_OFFS + 0x10)
#define CVP_FATAL_INTR_BMSK	(CVP_WRAPPER_INTR_MASK_CPU_NOC_BMSK | \
				CVP_WRAPPER_INTR_MASK_CORE_NOC_BMSK )
#define CVP_WRAPPER_INTR_MASK_CPU_NOC_BMSK	0x40
#define CVP_WRAPPER_INTR_MASK_CORE_NOC_BMSK	0x20
#define CVP_WRAPPER_INTR_MASK_A2HWD_BMSK	0x8
#define CVP_WRAPPER_INTR_MASK_A2HCPU_BMSK	0x4
#define CVP_WRAPPER_INTR_MASK_A2HCPU_SHFT	0x2

#define CVP_WRAPPER_INTR_CLEAR		(CVP_WRAPPER_BASE_OFFS + 0x14)

#define CVP_WRAPPER_TZ_BASE_OFFS		0x000C0000

#define CVP_WRAPPER_INTR_CLEAR_A2HWD_BMSK	0x10
#define CVP_WRAPPER_INTR_CLEAR_A2HWD_SHFT	0x4
#define CVP_WRAPPER_INTR_CLEAR_A2H_BMSK	0x4
#define CVP_WRAPPER_INTR_CLEAR_A2H_SHFT	0x2
#define CVP_WRAPPER_CPU_STATUS		(CVP_WRAPPER_TZ_BASE_OFFS + 0x10)
#define CVP_WRAPPER_AXI_CLOCK_CONFIG	(CVP_WRAPPER_TZ_BASE_OFFS + 0x14)
#define CVP_WRAPPER_QNS4PDXFIFO_RESET	(CVP_WRAPPER_TZ_BASE_OFFS + 0x18)
#define CVP_WRAPPER_CPU_CGC_DIS	(CVP_WRAPPER_BASE_OFFS + 0x2010)

#define CVP_WRAPPER_CPU_CLOCK_CONFIG	(CVP_WRAPPER_BASE_OFFS + 0x50)
#define CVP_WRAPPER_DEBUG_BRIDGE_LPI_CONTROL	(CVP_WRAPPER_BASE_OFFS + 0x54)
#define CVP_WRAPPER_DEBUG_BRIDGE_LPI_STATUS	(CVP_WRAPPER_BASE_OFFS + 0x58)
#define CVP_WRAPPER_CPU_NOC_LPI_CONTROL		(CVP_WRAPPER_BASE_OFFS + 0x5C)
#define CVP_WRAPPER_CPU_NOC_LPI_STATUS		(CVP_WRAPPER_BASE_OFFS + 0x60)
#define CVP_WRAPPER_CORE_CLOCK_CONFIG		(CVP_WRAPPER_BASE_OFFS + 0x88)
//Aurora
#define CVP_WRAPPER_CORE_SW_RESET_TRIGGER		(CVP_WRAPPER_BASE_OFFS + 0x94)
#define CVP_WRAPPER_CORE_SW_RESET_H		(CVP_WRAPPER_BASE_OFFS + 0x98)
#define CVP_WRAPPER_CORE_SW_RESET_L		(CVP_WRAPPER_BASE_OFFS + 0x9C)




#define CVP_CTRL_INIT		CVP_CPU_CS_SCIACMD

#define CVP_CTRL_STATUS	CVP_CPU_CS_SCIACMDARG0
#define CVP_CTRL_INIT_STATUS__M \
		CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_STATUS_BMSK
#define CVP_CTRL_ERROR_STATUS__M \
		CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_ERROR_STATUS_BMSK
#define CVP_CTRL_INIT_IDLE_MSG_BMSK \
		CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_IDLE_MSG_BMSK
#define CVP_CTRL_STATUS_PC_READY \
		CVP_CPU_CS_SCIACMDARG0_HFI_CTRL_PC_READY


#define CVP_QTBL_INFO		CVP_CPU_CS_SCIACMDARG1

#define CVP_QTBL_ADDR		CVP_CPU_CS_SCIACMDARG2

#define CVP_VERSION_INFO	CVP_CPU_CS_SCIACMDARG3

#define CVP_SFR_ADDR		CVP_CPU_CS_SCIBCMD
#define CVP_MMAP_ADDR		CVP_CPU_CS_SCIBCMDARG0
#define CVP_UC_REGION_ADDR	CVP_CPU_CS_SCIBARG1
#define CVP_UC_REGION_SIZE	CVP_CPU_CS_SCIBARG2

/* HFI_DSP_QTBL_ADDR
 * 31:3 - HFI_DSP_QTBL_ADDR
 *        4-byte aligned Address
 */
#define HFI_DSP_QTBL_ADDR	CVP_CPU_CS_VMIMSG

/* HFI_DSP_UC_REGION_ADDR
 * 31:20 - HFI_DSP_UC_REGION_ADDR
 *         1MB aligned address.
 *         Uncached Region start Address. This region covers
 *         HFI DSP QTable,
 *         HFI DSP Queue Headers,
 *         HFI DSP Queues,
 */
#define HFI_DSP_UC_REGION_ADDR	CVP_CPU_CS_VMIMSGAG0

/* HFI_DSP_UC_REGION_SIZE
 * 31:20 - HFI_DSP_UC_REGION_SIZE
 *         Multiples of 1MB.
 *         Size of the DSP_UC_REGION Uncached Region
 */
#define HFI_DSP_UC_REGION_SIZE	CVP_CPU_CS_VMIMSGAG1

/*
 * --------------------------------------------------------------------------
 * MODULE: vcodec noc error log registers
 * --------------------------------------------------------------------------
 */
#define CVP_NOC_BASE_OFFS		0x000D0000
#define CVP_NOC_ERR_SWID_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x0)
#define CVP_NOC_ERR_SWID_HIGH_OFFS	(CVP_NOC_BASE_OFFS + 0x4)
#define CVP_NOC_ERR_MAINCTL_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x8)
#define CVP_NOC_ERR_ERRVLD_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x10)
#define CVP_NOC_ERR_ERRCLR_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x18)
#define CVP_NOC_ERR_ERRLOG0_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x20)
#define CVP_NOC_ERR_ERRLOG0_HIGH_OFFS	(CVP_NOC_BASE_OFFS + 0x24)
#define CVP_NOC_ERR_ERRLOG1_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x28)
#define CVP_NOC_ERR_ERRLOG1_HIGH_OFFS	(CVP_NOC_BASE_OFFS + 0x2C)
#define CVP_NOC_ERR_ERRLOG2_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x30)
#define CVP_NOC_ERR_ERRLOG2_HIGH_OFFS	(CVP_NOC_BASE_OFFS + 0x34)
#define CVP_NOC_ERR_ERRLOG3_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x38)
#define CVP_NOC_ERR_ERRLOG3_HIGH_OFFS	(CVP_NOC_BASE_OFFS + 0x3C)
#define CVP_NOC_SBM_SENSELN0_LOW	(CVP_NOC_BASE_OFFS + 0x300)
#define CVP_NOC_CPU_PENDING_MASK	0x3F80000

#define CVP_NOC_CORE_BASE_OFFS			0x00010000
#define CVP_NOC_MAIN_SIDEBANDMANAGER_SENSELN0_LOW \
		(CVP_NOC_CORE_BASE_OFFS + 0x300)
#define CVP_NOC_MAIN_SIDEBANDMANAGER_SENSELN0_HIGH \
		(CVP_NOC_CORE_BASE_OFFS + 0x304)
#define CVP_NOC_MAIN_SIDEBANDMANAGER_SENSELN1_HIGH \
		(CVP_NOC_CORE_BASE_OFFS + 0x30C)
#define CVP_NOC_CORE_ERR_SWID_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x0)
#define CVP_NOC_CORE_ERR_SWID_HIGH_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x4)
#define CVP_NOC_CORE_ERR_MAINCTL_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x8)
#define CVP_NOC_CORE_ERR_ERRVLD_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x10)
#define CVP_NOC_CORE_ERR_ERRCLR_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x18)
#define CVP_NOC_CORE_ERR_ERRLOG0_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x20)
#define CVP_NOC_CORE_ERR_ERRLOG0_HIGH_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x24)
#define CVP_NOC_CORE_ERR_ERRLOG1_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x28)
#define CVP_NOC_CORE_ERR_ERRLOG1_HIGH_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x2C)
#define CVP_NOC_CORE_ERR_ERRLOG2_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x30)
#define CVP_NOC_CORE_ERR_ERRLOG2_HIGH_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x34)
#define CVP_NOC_CORE_ERR_ERRLOG3_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x38)
#define CVP_NOC_CORE_ERR_ERRLOG3_HIGH_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x3C)
#define CVP_NOC_PRIORITYLUT_LOW \
		(CVP_NOC_CORE_BASE_OFFS + 0x3030)
#define CVP_NOC_PRIORITYLUT_HIGH \
		(CVP_NOC_CORE_BASE_OFFS + 0x3034)
#define CVP_NOC_URGENCY_LOW \
		(CVP_NOC_CORE_BASE_OFFS + 0x3038)
#define CVP_NOC_DANGERLUT_LOW \
		(CVP_NOC_CORE_BASE_OFFS + 0x3040)
#define CVP_NOC_SAFELUT_LOW \
		(CVP_NOC_CORE_BASE_OFFS + 0x3048)
#define CVP_NOC_RESET_REQ \
		(CVP_NOC_CORE_BASE_OFFS + 0xf000)
#define CVP_NOC_RESET_ACK \
		(CVP_NOC_CORE_BASE_OFFS + 0xf004)


#define CVP_AON_WRAPPER_CVP_NOC_LPI_CONTROL	(CVP_AON_BASE_OFFS + 0x8)
#define CVP_AON_WRAPPER_CVP_NOC_LPI_STATUS	(CVP_AON_BASE_OFFS + 0xC)
#ifdef EVA_LSR//LSR regs
#define CVP_AON_WRAPPER_LSR_NOC_LPI_CONTROL	(CVP_AON_BASE_OFFS + 0x10)
#define CVP_AON_WRAPPER_LSR_NOC_LPI_STATUS	(CVP_AON_BASE_OFFS + 0x14)
#endif
#define CVP_CC_BASE_OFFS			0x000F8000
#define CVP_CC_MVS1C_GDSCR			(CVP_CC_BASE_OFFS + 0x78)
#define CVP_CC_MVS1C_CBCR			(CVP_CC_BASE_OFFS + 0x90)
#define CVP_CC_MVS1_GDSCR			(CVP_CC_BASE_OFFS + 0xCC)
#define CVP_CC_MVS1_CBCR			(CVP_CC_BASE_OFFS + 0xE0)

#define CVP_VIDEO_CC_MVS1C_DIV_DCDR       (CVP_CC_BASE_OFFS + 0x8C)
#define CVP_VIDEO_CC_XO_CBCR              (CVP_CC_BASE_OFFS + 0x124)

#ifdef EVA_LSR//LSR regs
/*
 * --------------------------------------------------------------------------
 * MODULE: LSR Video C NOC registers
 * --------------------------------------------------------------------------
 */
#define LSR_NOC_VIDEO_C_NOC         0x00030000

#define LSR_NOC_CSC_GCX_L_PRIORITYLUT_LOW \
		(LSR_NOC_VIDEO_C_NOC + 0x4030)
#define LSR_NOC_CSC_GCX_L_PRIORITYLUT_HIGH \
		(LSR_NOC_VIDEO_C_NOC + 0x4034)
#define LSR_NOC_CSC_GCX_L_URGENCY_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4038)
#define LSR_NOC_CSC_GCX_L_DANGERLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4040)
#define LSR_NOC_CSC_GCX_L_SAFELUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4048)
#define LSR_NOC_CSC_GCX_R_PRIORITYLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4430)
#define LSR_NOC_CSC_GCX_R_PRIORITYLUT_HIGH \
       (LSR_NOC_VIDEO_C_NOC + 0x4434)
#define LSR_NOC_CSC_GCX_R_URGENCY_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4438)
#define LSR_NOC_CSC_GCX_R_DANGERLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4440)
#define LSR_NOC_CSC_GCX_R_SAFELUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4448)
#define LSR_NOC_DDL_L_PRIORITYLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4830)
#define LSR_NOC_DDL_L_PRIORITYLUT_HIGH \
       (LSR_NOC_VIDEO_C_NOC + 0x4834)
#define LSR_NOC_DDL_L_URGENCY_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4838)
#define LSR_NOC_DDL_L_DANGERLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4840)
#define LSR_NOC_DDL_L_SAFELUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4848)
#define LSR_NOC_DDL_R_PRIORITYLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4C30)
#define LSR_NOC_DDL_R_PRIORITYLUT_HIGH \
       (LSR_NOC_VIDEO_C_NOC + 0x4C34)
#define LSR_NOC_DDL_R_URGENCY_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4C38)
#define LSR_NOC_DDL_R_DANGERLUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4C40)
#define LSR_NOC_DDL_R_SAFELUT_LOW \
       (LSR_NOC_VIDEO_C_NOC + 0x4C48)

/*AON_LSR_NOC_RESET_REGISTERS*/
#define AON_LSR_NOC_RESET 0x0003F000

#define AON_WRAPPER_LSR_NOC_RESET_REQ \
       (AON_LSR_NOC_RESET + 0x0)
#define AON_WRAPPER_LSR_NOC_RESET_ACK \
       (AON_LSR_NOC_RESET + 0x4)

#endif


#define SPAD0_LPI_LB             0x192E8000
#define SPAD1_LPI_LB             0x192F0000
#define SPAD_BROADCAST_ORLPI_LB  0x19AF0000
#define SPAD_BROADCAST_ANDLPI_LB 0x19CF0000

#define SPAD0_LPI_LB_REG_SIZE             0x00008000
#define SPAD1_LPI_LB_REG_SIZE             0x00008000
#define SPAD_BROADCAST_ORLPI_LB_REG_SIZE  0x00008000
#define SPAD_BROADCAST_ANDLPI_LB_REG_SIZE 0x00008000

#define SPAD0_LPI_LB_IOVA             0xFFC00000
#define SPAD1_LPI_LB_IOVA             0xFFC10000
#define SPAD_BROADCAST_ORLPI_LB_IOVA  0xFFC20000
#define SPAD_BROADCAST_ANDLPI_LB_IOVA 0xFFC30000

#define CVP_CORE_POWER_STATUS	(CVP_WRAPPER_BASE_OFFS + 0x80)

#define CVP_GCC_VIDEO_AXI1_CBCR           (0x32024)
#define GCC_IRIS_SS_HF_AXI1_CBCR          (0x32030)
#define GCC_IRIS_SS_SPD_AXI1_CBCR         (0x60020)
#define GCC_DDRSS_SPAD_CBCR         	(0x60000)
/*SPAD Registers*/

#define SPAD0_LPI_LB_RAM_TIMING0                           0x000
#define SPAD0_LPI_LB_RAM_TIMING1                           0x004
#define SPAD0_LPI_LB_RAM_TIMING2                           0x008
#define SPAD0_LPI_LB_PCB_SLP_SEL0                          0x00c
#define SPAD0_LPI_LB_PCB_SLP_NRET_SEL0                     0x010
#define SPAD0_LPI_LB_PCB_SLP_SEL1                          0x014
#define SPAD0_LPI_LB_PCB_SLP_NRET_SEL1                     0x018
#define SPAD0_LPI_LB_PCB_WAKEUP_SEL0                       0x01c
#define SPAD0_LPI_LB_PCB_WAKEUP_SEL1                       0x020
#define SPAD0_LPI_LB_PCB_ENABLE                            0x034
#define SPAD0_LPI_LB_RAM_IDLE_THRESHOLD                    0x044
#define SPAD0_LPI_LB_PCB_CMD                               0x048
#define SPAD0_LPI_LB_COUNTER_SYNC_RATE                     0x04c
#define SPAD0_LPI_LB_RAMSLP_STATUS                         0x050
#define SPAD0_LPI_LB_PCB_PWR_STATUS0                       0x054
#define SPAD0_LPI_LB_PCB_PWR_STATUS1                       0x058
#define SPAD0_LPI_LB_PCB_PWR_STATUS2                       0x05c
#define SPAD0_LPI_LB_PCB_PWR_STATUS3                       0x060
#define SPAD0_LPI_LB_PRE_ARES_STATUS                       0x064
#define SPAD0_LPI_LB_DEBUG_CTRL0                           0x068
#define SPAD0_LPI_LB_DEBUG_CTRL1                           0x06c
#define SPAD0_LPI_LB_DEBUG_CTRL2                           0x070
#define SPAD0_LPI_LB_DEBUG_CTRL3                           0x074
#define SPAD0_LPI_LB_DEBUG_CTRL4                           0x078
#define SPAD0_LPI_LB_DEBUG_CTRL5                           0x07c
#define SPAD0_LPI_LB_PCBSLP_STATUS0                        0x080
#define SPAD0_LPI_LB_PCBSLP_STATUS1                        0x084
#define SPAD0_LPI_LB_PCBSLP_STATUS2                        0x088
#define SPAD0_LPI_LB_PCBSLP_STATUS3                        0x08c
#define SPAD0_LPI_LB_PCBSLP_STATUS4                        0x090
#define SPAD0_LPI_LB_PCBSLP_STATUS5                        0x094
#define SPAD0_LPI_LB_PCBSLP_STATUS6                        0x098
#define SPAD0_LPI_LB_CLK_EN_CFG                            0x104
#define SPAD0_LPI_LB_PRE_ARES_CTRL                         0x108
#define SPAD0_LPI_LB_ADDR_REGION_CFG0                      0x110
#define SPAD0_LPI_LB_ADDR_REGION_CFG1                      0x114
#define SPAD0_LPI_LB_ADDR_REGION_CFG2                      0x118
#define SPAD0_LPI_LB_ADDR_REGION_CFG3                      0x11c
#define SPAD0_LPI_LB_PERFMON_MODE                          0x120
#define SPAD0_LPI_LB_PERFMON_CORE_CLOCK_CTRL               0x124
#define SPAD0_LPI_LB_PERFMON_CFG_CLOCK_CTRL                0x128
#define SPAD0_LPI_LB_PERFMON_DEBUG_CTRL                    0x12c
#define SPAD0_LPI_LB_PERFMON_STATUS                        0x130
#define SPAD0_LPI_LB_PERFMON_CONFIGURATION_INFO            0x134
#define SPAD0_LPI_LB_PERFMON_COUNTER_0_CONFIG              0x138
#define SPAD0_LPI_LB_PERFMON_COUNTER_1_CONFIG              0x13c
#define SPAD0_LPI_LB_PERFMON_COUNTER_2_CONFIG              0x140
#define SPAD0_LPI_LB_PERFMON_COUNTER_3_CONFIG              0x144
#define SPAD0_LPI_LB_PERFMON_COUNTER_4_CONFIG              0x148
#define SPAD0_LPI_LB_PERFMON_COUNTER_5_CONFIG              0x14c
#define SPAD0_LPI_LB_PERFMON_COUNTER_6_CONFIG              0x150
#define SPAD0_LPI_LB_PERFMON_COUNTER_7_CONFIG              0x154
#define SPAD0_LPI_LB_PERFMON_COUNTER_8_CONFIG              0x158
#define SPAD0_LPI_LB_PERFMON_COUNTER_9_CONFIG              0x15c
#define SPAD0_LPI_LB_PERFMON_COUNTER_10_CONFIG             0x160
#define SPAD0_LPI_LB_PERFMON_COUNTER_11_CONFIG             0x164
#define SPAD0_LPI_LB_PERFMON_COUNTER_12_CONFIG             0x168
#define SPAD0_LPI_LB_PERFMON_COUNTER_13_CONFIG             0x16c
#define SPAD0_LPI_LB_PERFMON_COUNTER_14_CONFIG             0x170
#define SPAD0_LPI_LB_PERFMON_COUNTER_15_CONFIG             0x174
#define SPAD0_LPI_LB_PERFMON_COUNTER_0_VALUE               0x178
#define SPAD0_LPI_LB_PERFMON_COUNTER_1_VALUE               0x17c
#define SPAD0_LPI_LB_PERFMON_COUNTER_2_VALUE               0x180
#define SPAD0_LPI_LB_PERFMON_COUNTER_3_VALUE               0x184
#define SPAD0_LPI_LB_PERFMON_COUNTER_4_VALUE               0x188
#define SPAD0_LPI_LB_PERFMON_COUNTER_5_VALUE               0x18c
#define SPAD0_LPI_LB_PERFMON_COUNTER_6_VALUE               0x190
#define SPAD0_LPI_LB_PERFMON_COUNTER_7_VALUE               0x194
#define SPAD0_LPI_LB_PERFMON_COUNTER_8_VALUE               0x198
#define SPAD0_LPI_LB_PERFMON_COUNTER_9_VALUE               0x19c
#define SPAD0_LPI_LB_PERFMON_COUNTER_10_VALUE              0x1a0
#define SPAD0_LPI_LB_PERFMON_COUNTER_11_VALUE              0x1a4
#define SPAD0_LPI_LB_PERFMON_COUNTER_12_VALUE              0x1a8
#define SPAD0_LPI_LB_PERFMON_COUNTER_13_VALUE              0x1ac
#define SPAD0_LPI_LB_PERFMON_COUNTER_14_VALUE              0x1b0
#define SPAD0_LPI_LB_PERFMON_COUNTER_15_VALUE              0x1b4
#define SPAD0_LPI_LB_PERFMON_COUNTER_0_OVERFLOW            0x1b8
#define SPAD0_LPI_LB_PERFMON_COUNTER_1_OVERFLOW            0x1bc
#define SPAD0_LPI_LB_PERFMON_COUNTER_2_OVERFLOW            0x1c0
#define SPAD0_LPI_LB_PERFMON_COUNTER_3_OVERFLOW            0x1c4
#define SPAD0_LPI_LB_PERFMON_COUNTER_4_OVERFLOW            0x1c8
#define SPAD0_LPI_LB_PERFMON_COUNTER_5_OVERFLOW            0x1cc
#define SPAD0_LPI_LB_PERFMON_COUNTER_6_OVERFLOW            0x1d0
#define SPAD0_LPI_LB_PERFMON_COUNTER_7_OVERFLOW            0x1d4
#define SPAD0_LPI_LB_PERFMON_COUNTER_8_OVERFLOW            0x1d8
#define SPAD0_LPI_LB_PERFMON_COUNTER_9_OVERFLOW            0x1dc
#define SPAD0_LPI_LB_PERFMON_COUNTER_10_OVERFLOW           0x1e0
#define SPAD0_LPI_LB_PERFMON_COUNTER_11_OVERFLOW           0x1e4
#define SPAD0_LPI_LB_PERFMON_COUNTER_12_OVERFLOW           0x1e8
#define SPAD0_LPI_LB_PERFMON_COUNTER_13_OVERFLOW           0x1ec
#define SPAD0_LPI_LB_PERFMON_COUNTER_14_OVERFLOW           0x1f0
#define SPAD0_LPI_LB_PERFMON_COUNTER_15_OVERFLOW           0x1f4
#define SPAD0_LPI_LB_PRED_WAKEUP_EN                        0x284
#define SPAD0_LPI_LB_PROF_FILTER_0_CFG                     0x288
#define SPAD0_LPI_LB_PROF_FILTER_1_CFG                     0x28c
#define SPAD0_LPI_LB_DRP_ECC_ERROR_CFG                     0x1000
#define SPAD0_LPI_LB_DEBUG_CTRL                            0x1008
#define SPAD0_LPI_LB_DRP_ECC_ERROR_INJECTION_0             0x1010
#define SPAD0_LPI_LB_DRP_ECC_ERROR_INJECTION_1             0x1014
#define SPAD0_LPI_LB_DEBUG_TESTBUS                         0x1018
#define SPAD0_LPI_LB_HW_EVENT_CTRL                         0x101c
#define SPAD0_LPI_LB_DRP_INTERRUPT_STATUS                  0x1020
#define SPAD0_LPI_LB_DRP_INTERRUPT_ENABLE                  0x102c
#define SPAD0_LPI_LB_DRP_CH0_ECC_ERROR_STATUS              0x1034
#define SPAD0_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN0               0x1038
#define SPAD0_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN1               0x103c
#define SPAD0_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN2               0x1040
#define SPAD0_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN3               0x1044
#define SPAD0_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN4               0x1048
#define SPAD0_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN5               0x104c
#define SPAD0_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN6               0x1050
#define SPAD0_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN0               0x1058
#define SPAD0_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN1               0x105c
#define SPAD0_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN2               0x1060
#define SPAD0_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN3               0x1064
#define SPAD0_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN4               0x1068
#define SPAD0_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN5               0x106c
#define SPAD0_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN6               0x1074
#define SPAD0_LPI_LB_DRP_FIFO_EMPTY_STATUS                 0x1078
#define SPAD0_LPI_LB_DRP_FIFO_FULL_STATUS                  0x107c
#define SPAD0_LPI_LB_ADDR_DECODE_ERR_CFG                   0x1080
#define SPAD0_LPI_LB_ADDR_DECODE_ERR_INTERRUPT_STATUS      0x1084
#define SPAD0_LPI_LB_ADDR_DECODE_ERR_INTERRUPT_ENABLE      0x108c
#define SPAD0_LPI_LB_RD_ADDR_DECODE_ERR_STATUS1            0x1090
#define SPAD0_LPI_LB_RD_ADDR_DECODE_ERR_STATUS2            0x1094
#define SPAD0_LPI_LB_RD_ADDR_DECODE_ERR_STATUS3            0x1098
#define SPAD0_LPI_LB_RD_ADDR_DECODE_ERR_STATUS4            0x109c
#define SPAD0_LPI_LB_RD_ADDR_DECODE_ERR_STATUS5            0x10a0
#define SPAD0_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN7               0x10a4
#define SPAD0_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN8               0x10a8
#define SPAD0_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN9               0x10ac
#define SPAD0_LPI_LB_DRP_CH1_ECC_ERROR_STATUS              0x10b0
#define SPAD0_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN10              0x10b4
#define SPAD0_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN7               0x10b8
#define SPAD0_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN8               0x10bc
#define SPAD0_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN9               0x10c0
#define SPAD0_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN10              0x10c4
#define SPAD0_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN7               0x10c8
#define SPAD0_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN8               0x10cc
#define SPAD0_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN9               0x10d0
#define SPAD0_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN10              0x10d4
#define SPAD0_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN7               0x10d8
#define SPAD0_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN8               0x10dc
#define SPAD0_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN9               0x10e0
#define SPAD0_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN10              0x10e4
#define SPAD0_LPI_LB_WR_ADDR_DECODE_ERR_STATUS1            0x10e8
#define SPAD0_LPI_LB_WR_ADDR_DECODE_ERR_STATUS2            0x10ec
#define SPAD0_LPI_LB_WR_ADDR_DECODE_ERR_STATUS3            0x10f0
#define SPAD0_LPI_LB_WR_ADDR_DECODE_ERR_STATUS4            0x10f4
#define SPAD0_LPI_LB_WR_ADDR_DECODE_ERR_STATUS5            0x10f8
#define SPAD0_LPI_LB_DCRSW_CFG                             0x1110
#define SPAD0_LPI_LB_DCRSW_STATUS0                         0x1114
#define SPAD0_LPI_LB_DCRSW_STATUS1                         0x1118
#define SPAD0_LPI_LB_DCRSW_STATUS2                         0x111c
#define SPAD0_LPI_LB_DCRSW_STATUS3                         0x1120
#define SPAD0_LPI_LB_DCRSW_STATUS4                         0x1124
#define SPAD0_LPI_LB_DCRSW_STATUS5                         0x1128
#define SPAD0_LPI_LB_DCRSW_STATUS6                         0x112c
#define SPAD0_LPI_LB_DCRSW_STATUS7                         0x1130
#define SPAD0_LPI_LB_DCRSW_STATUS8                         0x1134
#define SPAD0_LPI_LB_IF_CHANNEL_STATUS                     0x1138
#define SPAD0_LPI_LB_FIFO_STATUS                           0x113c
#define SPAD0_LPI_LB_RSPPROC_CREDITS_STATUS                0x1140
#define SPAD0_LPI_LB_DBG_EVENT_STATUS                      0x118c
#define SPAD0_LPI_LB_DBG_EVENT_FWD                         0x1194
#define SPAD0_LPI_LB_UNS_ERR_CFG                           0x1200
#define SPAD0_LPI_LB_UNS_ERR_STATUS1                       0x1204
#define SPAD0_LPI_LB_UNS_ERR_STATUS2                       0x1208
#define SPAD0_LPI_LB_UNS_ERR_STATUS3                       0x120c
#define SPAD0_LPI_LB_UNS_ERR_STATUS4                       0x1210
#define SPAD0_LPI_LB_UNS_ERR_STATUS5                       0x1214
#define SPAD0_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN0               0x1218
#define SPAD0_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN1               0x121c
#define SPAD0_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN2               0x1220
#define SPAD0_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN3               0x1224
#define SPAD0_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN4               0x1228
#define SPAD0_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN5               0x122c
#define SPAD0_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN6               0x1230
#define SPAD0_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN0               0x1238
#define SPAD0_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN1               0x123c
#define SPAD0_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN2               0x1240
#define SPAD0_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN3               0x1244
#define SPAD0_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN4               0x1248
#define SPAD0_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN5               0x124c
#define SPAD0_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN6               0x1250
#define SPAD0_LPI_LB_FF_CLK_ON_CTRL                        0x1254
#define SPAD0_LPI_LB_BIST_CTRL                             0x2000
#define SPAD0_LPI_LB_BIST_CLK_CTRL                         0x2008
#define SPAD0_LPI_LB_BIST_WRITE_CONFIG1                    0x2010
#define SPAD0_LPI_LB_BIST_WRITE_CONFIG2                    0x2014
#define SPAD0_LPI_LB_BIST_WR_ADDR                          0x2018
#define SPAD0_LPI_LB_BIST_WR_BIST_SEED_31_0                0x201c
#define SPAD0_LPI_LB_BIST_WR_BIST_SEED_63_32               0x2020
#define SPAD0_LPI_LB_BIST_WR_BIST_SEED_95_64               0x2024
#define SPAD0_LPI_LB_BIST_WR_BIST_SEED_127_96              0x202c
#define SPAD0_LPI_LB_BIST_READ_CONFIG1                     0x2040
#define SPAD0_LPI_LB_BIST_READ_CONFIG2                     0x2044
#define SPAD0_LPI_LB_BIST_RD_ADDR                          0x2048
#define SPAD0_LPI_LB_BIST_RD_BIST_SEED_31_0                0x204c
#define SPAD0_LPI_LB_BIST_RD_BIST_SEED_63_32               0x2050
#define SPAD0_LPI_LB_BIST_RD_BIST_SEED_95_64               0x2054
#define SPAD0_LPI_LB_BIST_RD_BIST_SEED_127_96              0x2058
#define SPAD0_LPI_LB_BIST_LFSR_TAP_POINT                   0x206c
#define SPAD0_LPI_LB_BIST_STATUS                           0x2070
#define SPAD0_LPI_LB_BIST_FAILURE                          0x2074
#define SPAD0_LPI_LB_BIST_FAILURE_0_BITS                   0x2078
#define SPAD0_LPI_LB_BIST_FAILURE_1_BITS                   0x207c
#define SPAD0_LPI_LB_BIST_FAILURE_2_BITS                   0x2080
#define SPAD0_LPI_LB_BIST_FAILURE_3_BITS                   0x2084
#define SPAD0_LPI_LB_BIST_FAILURE_4_BITS                   0x2088
#define SPAD0_LPI_LB_BIST_FAILURE_5_BITS                   0x208c
#define SPAD0_LPI_LB_BIST_SPARE                            0x20a0
#define SPAD0_LPI_LB_BIST_TAG_RAM_EXTRA_COL_ACT            0x20a4

#define SPAD1_LPI_LB_RAM_TIMING0                           0x0000
#define SPAD1_LPI_LB_RAM_TIMING1                           0x0004
#define SPAD1_LPI_LB_RAM_TIMING2                           0x0008
#define SPAD1_LPI_LB_PCB_SLP_SEL0                          0x000c
#define SPAD1_LPI_LB_PCB_SLP_NRET_SEL0                     0x0010
#define SPAD1_LPI_LB_PCB_SLP_SEL1                          0x0014
#define SPAD1_LPI_LB_PCB_SLP_NRET_SEL1                     0x0018
#define SPAD1_LPI_LB_PCB_WAKEUP_SEL0                       0x001c
#define SPAD1_LPI_LB_PCB_WAKEUP_SEL1                       0x0020
#define SPAD1_LPI_LB_PCB_ENABLE                            0x0034
#define SPAD1_LPI_LB_RAM_IDLE_THRESHOLD                    0x0044
#define SPAD1_LPI_LB_PCB_CMD                               0x0048
#define SPAD1_LPI_LB_COUNTER_SYNC_RATE                     0x004c
#define SPAD1_LPI_LB_RAMSLP_STATUS                         0x0050
#define SPAD1_LPI_LB_PCB_PWR_STATUS0                       0x0054
#define SPAD1_LPI_LB_PCB_PWR_STATUS1                       0x0058
#define SPAD1_LPI_LB_PCB_PWR_STATUS2                       0x005c
#define SPAD1_LPI_LB_PCB_PWR_STATUS3                       0x0060
#define SPAD1_LPI_LB_PRE_ARES_STATUS                       0x0064
#define SPAD1_LPI_LB_DEBUG_CTRL0                           0x0068
#define SPAD1_LPI_LB_DEBUG_CTRL1                           0x006c
#define SPAD1_LPI_LB_DEBUG_CTRL2                           0x0070
#define SPAD1_LPI_LB_DEBUG_CTRL3                           0x0074
#define SPAD1_LPI_LB_DEBUG_CTRL4                           0x0078
#define SPAD1_LPI_LB_DEBUG_CTRL5                           0x007c
#define SPAD1_LPI_LB_PCBSLP_STATUS0                        0x0080
#define SPAD1_LPI_LB_PCBSLP_STATUS1                        0x0084
#define SPAD1_LPI_LB_PCBSLP_STATUS2                        0x0088
#define SPAD1_LPI_LB_PCBSLP_STATUS3                        0x008c
#define SPAD1_LPI_LB_PCBSLP_STATUS4                        0x0090
#define SPAD1_LPI_LB_PCBSLP_STATUS5                        0x0094
#define SPAD1_LPI_LB_PCBSLP_STATUS6                        0x0098
#define SPAD1_LPI_LB_CLK_EN_CFG                            0x0104
#define SPAD1_LPI_LB_PRE_ARES_CTRL                         0x0108
#define SPAD1_LPI_LB_ADDR_REGION_CFG0                      0x0110
#define SPAD1_LPI_LB_ADDR_REGION_CFG1                      0x0114
#define SPAD1_LPI_LB_ADDR_REGION_CFG2                      0x0118
#define SPAD1_LPI_LB_ADDR_REGION_CFG3                      0x011c
#define SPAD1_LPI_LB_PERFMON_MODE                          0x0120
#define SPAD1_LPI_LB_PERFMON_CORE_CLOCK_CTRL               0x0124
#define SPAD1_LPI_LB_PERFMON_CFG_CLOCK_CTRL                0x0128
#define SPAD1_LPI_LB_PERFMON_DEBUG_CTRL                    0x012c
#define SPAD1_LPI_LB_PERFMON_STATUS                        0x0130
#define SPAD1_LPI_LB_PERFMON_CONFIGURATION_INFO            0x0134
#define SPAD1_LPI_LB_PERFMON_COUNTER_0_CONFIG              0x0138
#define SPAD1_LPI_LB_PERFMON_COUNTER_1_CONFIG              0x013c
#define SPAD1_LPI_LB_PERFMON_COUNTER_2_CONFIG              0x0140
#define SPAD1_LPI_LB_PERFMON_COUNTER_3_CONFIG              0x0144
#define SPAD1_LPI_LB_PERFMON_COUNTER_4_CONFIG              0x0148
#define SPAD1_LPI_LB_PERFMON_COUNTER_5_CONFIG              0x014c
#define SPAD1_LPI_LB_PERFMON_COUNTER_6_CONFIG              0x0150
#define SPAD1_LPI_LB_PERFMON_COUNTER_7_CONFIG              0x0154
#define SPAD1_LPI_LB_PERFMON_COUNTER_8_CONFIG              0x0158
#define SPAD1_LPI_LB_PERFMON_COUNTER_9_CONFIG              0x015c
#define SPAD1_LPI_LB_PERFMON_COUNTER_10_CONFIG             0x0160
#define SPAD1_LPI_LB_PERFMON_COUNTER_11_CONFIG             0x0164
#define SPAD1_LPI_LB_PERFMON_COUNTER_12_CONFIG             0x0168
#define SPAD1_LPI_LB_PERFMON_COUNTER_13_CONFIG             0x016c
#define SPAD1_LPI_LB_PERFMON_COUNTER_14_CONFIG             0x0170
#define SPAD1_LPI_LB_PERFMON_COUNTER_15_CONFIG             0x0174
#define SPAD1_LPI_LB_PERFMON_COUNTER_0_VALUE               0x0178
#define SPAD1_LPI_LB_PERFMON_COUNTER_1_VALUE               0x017c
#define SPAD1_LPI_LB_PERFMON_COUNTER_2_VALUE               0x0180
#define SPAD1_LPI_LB_PERFMON_COUNTER_3_VALUE               0x0184
#define SPAD1_LPI_LB_PERFMON_COUNTER_4_VALUE               0x0188
#define SPAD1_LPI_LB_PERFMON_COUNTER_5_VALUE               0x018c
#define SPAD1_LPI_LB_PERFMON_COUNTER_6_VALUE               0x0190
#define SPAD1_LPI_LB_PERFMON_COUNTER_7_VALUE               0x0194
#define SPAD1_LPI_LB_PERFMON_COUNTER_8_VALUE               0x0198
#define SPAD1_LPI_LB_PERFMON_COUNTER_9_VALUE               0x019c
#define SPAD1_LPI_LB_PERFMON_COUNTER_10_VALUE              0x01a0
#define SPAD1_LPI_LB_PERFMON_COUNTER_11_VALUE              0x01a4
#define SPAD1_LPI_LB_PERFMON_COUNTER_12_VALUE              0x01a8
#define SPAD1_LPI_LB_PERFMON_COUNTER_13_VALUE              0x01ac
#define SPAD1_LPI_LB_PERFMON_COUNTER_14_VALUE              0x01b0
#define SPAD1_LPI_LB_PERFMON_COUNTER_15_VALUE              0x01b4
#define SPAD1_LPI_LB_PERFMON_COUNTER_0_OVERFLOW            0x01b8
#define SPAD1_LPI_LB_PERFMON_COUNTER_1_OVERFLOW            0x01bc
#define SPAD1_LPI_LB_PERFMON_COUNTER_2_OVERFLOW            0x01c0
#define SPAD1_LPI_LB_PERFMON_COUNTER_3_OVERFLOW            0x01c4
#define SPAD1_LPI_LB_PERFMON_COUNTER_4_OVERFLOW            0x01c8
#define SPAD1_LPI_LB_PERFMON_COUNTER_5_OVERFLOW            0x01cc
#define SPAD1_LPI_LB_PERFMON_COUNTER_6_OVERFLOW            0x01d0
#define SPAD1_LPI_LB_PERFMON_COUNTER_7_OVERFLOW            0x01d4
#define SPAD1_LPI_LB_PERFMON_COUNTER_8_OVERFLOW            0x01d8
#define SPAD1_LPI_LB_PERFMON_COUNTER_9_OVERFLOW            0x01dc
#define SPAD1_LPI_LB_PERFMON_COUNTER_10_OVERFLOW           0x01e0
#define SPAD1_LPI_LB_PERFMON_COUNTER_11_OVERFLOW           0x01e4
#define SPAD1_LPI_LB_PERFMON_COUNTER_12_OVERFLOW           0x01e8
#define SPAD1_LPI_LB_PERFMON_COUNTER_13_OVERFLOW           0x01ec
#define SPAD1_LPI_LB_PERFMON_COUNTER_14_OVERFLOW           0x01f0
#define SPAD1_LPI_LB_PERFMON_COUNTER_15_OVERFLOW           0x01f4
#define SPAD1_LPI_LB_PRED_WAKEUP_EN                        0x0284
#define SPAD1_LPI_LB_PROF_FILTER_0_CFG                     0x0288
#define SPAD1_LPI_LB_PROF_FILTER_1_CFG                     0x028c
#define SPAD1_LPI_LB_DRP_ECC_ERROR_CFG                     0x1000
#define SPAD1_LPI_LB_DEBUG_CTRL                            0x1008
#define SPAD1_LPI_LB_DRP_ECC_ERROR_INJECTION_0             0x1010
#define SPAD1_LPI_LB_DRP_ECC_ERROR_INJECTION_1             0x1014
#define SPAD1_LPI_LB_DEBUG_TESTBUS                         0x1018
#define SPAD1_LPI_LB_HW_EVENT_CTRL                         0x101c
#define SPAD1_LPI_LB_DRP_INTERRUPT_STATUS                  0x1020
#define SPAD1_LPI_LB_DRP_INTERRUPT_ENABLE                  0x102c
#define SPAD1_LPI_LB_DRP_CH0_ECC_ERROR_STATUS              0x1034
#define SPAD1_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN0               0x1038
#define SPAD1_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN1               0x103c
#define SPAD1_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN2               0x1040
#define SPAD1_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN3               0x1044
#define SPAD1_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN4               0x1048
#define SPAD1_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN5               0x104c
#define SPAD1_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN6               0x1050
#define SPAD1_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN0               0x1058
#define SPAD1_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN1               0x105c
#define SPAD1_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN2               0x1060
#define SPAD1_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN3               0x1064
#define SPAD1_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN4               0x1068
#define SPAD1_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN5               0x106c
#define SPAD1_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN6               0x1074
#define SPAD1_LPI_LB_DRP_FIFO_EMPTY_STATUS                 0x1078
#define SPAD1_LPI_LB_DRP_FIFO_FULL_STATUS                  0x107c
#define SPAD1_LPI_LB_ADDR_DECODE_ERR_CFG                   0x1080
#define SPAD1_LPI_LB_ADDR_DECODE_ERR_INTERRUPT_STATUS      0x1084
#define SPAD1_LPI_LB_ADDR_DECODE_ERR_INTERRUPT_ENABLE      0x108c
#define SPAD1_LPI_LB_RD_ADDR_DECODE_ERR_STATUS1            0x1090
#define SPAD1_LPI_LB_RD_ADDR_DECODE_ERR_STATUS2            0x1094
#define SPAD1_LPI_LB_RD_ADDR_DECODE_ERR_STATUS3            0x1098
#define SPAD1_LPI_LB_RD_ADDR_DECODE_ERR_STATUS4            0x109c
#define SPAD1_LPI_LB_RD_ADDR_DECODE_ERR_STATUS5            0x10a0
#define SPAD1_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN7               0x10a4
#define SPAD1_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN8               0x10a8
#define SPAD1_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN9               0x10ac
#define SPAD1_LPI_LB_DRP_CH1_ECC_ERROR_STATUS              0x10b0
#define SPAD1_LPI_LB_DRP_CH0_ECC_SB_ERR_SYN10              0x10b4
#define SPAD1_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN7               0x10b8
#define SPAD1_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN8               0x10bc
#define SPAD1_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN9               0x10c0
#define SPAD1_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN10              0x10c4
#define SPAD1_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN7               0x10c8
#define SPAD1_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN8               0x10cc
#define SPAD1_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN9               0x10d0
#define SPAD1_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN10              0x10d4
#define SPAD1_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN7               0x10d8
#define SPAD1_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN8               0x10dc
#define SPAD1_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN9               0x10e0
#define SPAD1_LPI_LB_DRP_CH0_ECC_DB_ERR_SYN10              0x10e4
#define SPAD1_LPI_LB_WR_ADDR_DECODE_ERR_STATUS1            0x10e8
#define SPAD1_LPI_LB_WR_ADDR_DECODE_ERR_STATUS2            0x10ec
#define SPAD1_LPI_LB_WR_ADDR_DECODE_ERR_STATUS3            0x10f0
#define SPAD1_LPI_LB_WR_ADDR_DECODE_ERR_STATUS4            0x10f4
#define SPAD1_LPI_LB_WR_ADDR_DECODE_ERR_STATUS5            0x10f8
#define SPAD1_LPI_LB_DCRSW_CFG                             0x1110
#define SPAD1_LPI_LB_DCRSW_STATUS0                         0x1114
#define SPAD1_LPI_LB_DCRSW_STATUS1                         0x1118
#define SPAD1_LPI_LB_DCRSW_STATUS2                         0x111c
#define SPAD1_LPI_LB_DCRSW_STATUS3                         0x1120
#define SPAD1_LPI_LB_DCRSW_STATUS4                         0x1124
#define SPAD1_LPI_LB_DCRSW_STATUS5                         0x1128
#define SPAD1_LPI_LB_DCRSW_STATUS6                         0x112c
#define SPAD1_LPI_LB_DCRSW_STATUS7                         0x1130
#define SPAD1_LPI_LB_DCRSW_STATUS8                         0x1134
#define SPAD1_LPI_LB_IF_CHANNEL_STATUS                     0x1138
#define SPAD1_LPI_LB_FIFO_STATUS                           0x113c
#define SPAD1_LPI_LB_RSPPROC_CREDITS_STATUS                0x1140
#define SPAD1_LPI_LB_DBG_EVENT_STATUS                      0x118c
#define SPAD1_LPI_LB_DBG_EVENT_FWD                         0x1194
#define SPAD1_LPI_LB_UNS_ERR_CFG                           0x1200
#define SPAD1_LPI_LB_UNS_ERR_STATUS1                       0x1204
#define SPAD1_LPI_LB_UNS_ERR_STATUS2                       0x1208
#define SPAD1_LPI_LB_UNS_ERR_STATUS3                       0x120c
#define SPAD1_LPI_LB_UNS_ERR_STATUS4                       0x1210
#define SPAD1_LPI_LB_UNS_ERR_STATUS5                       0x1214
#define SPAD1_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN0               0x1218
#define SPAD1_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN1               0x121c
#define SPAD1_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN2               0x1220
#define SPAD1_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN3               0x1224
#define SPAD1_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN4               0x1228
#define SPAD1_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN5               0x122c
#define SPAD1_LPI_LB_DRP_CH1_ECC_SB_ERR_SYN6               0x1230
#define SPAD1_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN0               0x1238
#define SPAD1_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN1               0x123c
#define SPAD1_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN2               0x1240
#define SPAD1_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN3               0x1244
#define SPAD1_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN4               0x1248
#define SPAD1_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN5               0x124c
#define SPAD1_LPI_LB_DRP_CH1_ECC_DB_ERR_SYN6               0x1250
#define SPAD1_LPI_LB_FF_CLK_ON_CTRL                        0x1254
#define SPAD1_LPI_LB_BIST_CTRL                             0x2000
#define SPAD1_LPI_LB_BIST_CLK_CTRL                         0x2008
#define SPAD1_LPI_LB_BIST_WRITE_CONFIG1                    0x2010
#define SPAD1_LPI_LB_BIST_WRITE_CONFIG2                    0x2014
#define SPAD1_LPI_LB_BIST_WR_ADDR                          0x2018
#define SPAD1_LPI_LB_BIST_WR_BIST_SEED_31_0                0x201c
#define SPAD1_LPI_LB_BIST_WR_BIST_SEED_63_32               0x2020
#define SPAD1_LPI_LB_BIST_WR_BIST_SEED_95_64               0x2024
#define SPAD1_LPI_LB_BIST_WR_BIST_SEED_127_96              0x202c
#define SPAD1_LPI_LB_BIST_READ_CONFIG1                     0x2040
#define SPAD1_LPI_LB_BIST_READ_CONFIG2                     0x2044
#define SPAD1_LPI_LB_BIST_RD_ADDR                          0x2048
#define SPAD1_LPI_LB_BIST_RD_BIST_SEED_31_0                0x204c
#define SPAD1_LPI_LB_BIST_RD_BIST_SEED_63_32               0x2050
#define SPAD1_LPI_LB_BIST_RD_BIST_SEED_95_64               0x2054
#define SPAD1_LPI_LB_BIST_RD_BIST_SEED_127_96              0x2058
#define SPAD1_LPI_LB_BIST_LFSR_TAP_POINT                   0x206c
#define SPAD1_LPI_LB_BIST_STATUS                           0x2070
#define SPAD1_LPI_LB_BIST_FAILURE                          0x2074
#define SPAD1_LPI_LB_BIST_FAILURE_0_BITS                   0x2078
#define SPAD1_LPI_LB_BIST_FAILURE_1_BITS                   0x207c
#define SPAD1_LPI_LB_BIST_FAILURE_2_BITS                   0x2080
#define SPAD1_LPI_LB_BIST_FAILURE_3_BITS                   0x2084
#define SPAD1_LPI_LB_BIST_FAILURE_4_BITS                   0x2088
#define SPAD1_LPI_LB_BIST_FAILURE_5_BITS                   0x208c
#define SPAD1_LPI_LB_BIST_SPARE                            0x20a0
#define SPAD1_LPI_LB_BIST_TAG_RAM_EXTRA_COL_ACT            0x20a4

#define  SPAD_BROADCAST_ORLPI_LB_RAM_TIMING0                        0x0000
#define  SPAD_BROADCAST_ORLPI_LB_RAM_TIMING1                        0x0004
#define  SPAD_BROADCAST_ORLPI_LB_RAM_TIMING2                        0x0008
#define  SPAD_BROADCAST_ORLPI_LB_PCB_SLP_SEL0                       0x000c
#define  SPAD_BROADCAST_ORLPI_LB_PCB_SLP_NRET_SEL0                  0x0010
#define  SPAD_BROADCAST_ORLPI_LB_PCB_SLP_SEL1                       0x0014
#define  SPAD_BROADCAST_ORLPI_LB_PCB_SLP_NRET_SEL1                  0x0018
#define  SPAD_BROADCAST_ORLPI_LB_PCB_WAKEUP_SEL0                    0x001c
#define  SPAD_BROADCAST_ORLPI_LB_PCB_WAKEUP_SEL1                    0x0020
#define  SPAD_BROADCAST_ORLPI_LB_PCB_ENABLE                         0x0034
#define  SPAD_BROADCAST_ORLPI_LB_RAM_IDLE_THRESHOLD                 0x0044
#define  SPAD_BROADCAST_ORLPI_LB_PCB_CMD                            0x0048
#define  SPAD_BROADCAST_ORLPI_LB_COUNTER_SYNC_RATE                  0x004c
#define  SPAD_BROADCAST_ORLPI_LB_RAMSLP_STATUS                      0x0050
#define  SPAD_BROADCAST_ORLPI_LB_PCB_PWR_STATUS0                    0x0054
#define  SPAD_BROADCAST_ORLPI_LB_PCB_PWR_STATUS1                    0x0058
#define  SPAD_BROADCAST_ORLPI_LB_PCB_PWR_STATUS2                    0x005c
#define  SPAD_BROADCAST_ORLPI_LB_PCB_PWR_STATUS3                    0x0060
#define  SPAD_BROADCAST_ORLPI_LB_PRE_ARES_STATUS                    0x0064
#define  SPAD_BROADCAST_ORLPI_LB_DEBUG_CTRL0                        0x0068
#define  SPAD_BROADCAST_ORLPI_LB_DEBUG_CTRL1                        0x006c
#define  SPAD_BROADCAST_ORLPI_LB_DEBUG_CTRL2                        0x0070
#define  SPAD_BROADCAST_ORLPI_LB_DEBUG_CTRL3                        0x0074
#define  SPAD_BROADCAST_ORLPI_LB_DEBUG_CTRL4                        0x0078
#define  SPAD_BROADCAST_ORLPI_LB_DEBUG_CTRL5                        0x007c
#define  SPAD_BROADCAST_ORLPI_LB_PCBSLP_STATUS0                     0x0080
#define  SPAD_BROADCAST_ORLPI_LB_PCBSLP_STATUS1                     0x0084
#define  SPAD_BROADCAST_ORLPI_LB_PCBSLP_STATUS2                     0x0088
#define  SPAD_BROADCAST_ORLPI_LB_PCBSLP_STATUS3                     0x008c
#define  SPAD_BROADCAST_ORLPI_LB_PCBSLP_STATUS4                     0x0090
#define  SPAD_BROADCAST_ORLPI_LB_PCBSLP_STATUS5                     0x0094
#define  SPAD_BROADCAST_ORLPI_LB_PCBSLP_STATUS6                     0x0098
#define  SPAD_BROADCAST_ORLPI_LB_CLK_EN_CFG                         0x0104
#define  SPAD_BROADCAST_ORLPI_LB_PRE_ARES_CTRL                      0x0108
#define  SPAD_BROADCAST_ORLPI_LB_ADDR_REGION_CFG0                   0x0110
#define  SPAD_BROADCAST_ORLPI_LB_ADDR_REGION_CFG1                   0x0114
#define  SPAD_BROADCAST_ORLPI_LB_ADDR_REGION_CFG2                   0x0118
#define  SPAD_BROADCAST_ORLPI_LB_ADDR_REGION_CFG3                   0x011c
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_MODE                       0x0120
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_CORE_CLOCK_CTRL            0x0124
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_CFG_CLOCK_CTRL             0x0128
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_DEBUG_CTRL                 0x012c
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_STATUS                     0x0130
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_CONFIGURATION_INFO         0x0134
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_0_CONFIG           0x0138
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_1_CONFIG           0x013c
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_2_CONFIG           0x0140
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_3_CONFIG           0x0144
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_4_CONFIG           0x0148
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_5_CONFIG           0x014c
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_6_CONFIG           0x0150
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_7_CONFIG           0x0154
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_8_CONFIG           0x0158
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_9_CONFIG           0x015c
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_10_CONFIG          0x0160
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_11_CONFIG          0x0164
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_12_CONFIG          0x0168
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_13_CONFIG          0x016c
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_14_CONFIG          0x0170
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_15_CONFIG          0x0174
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_0_VALUE            0x0178
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_1_VALUE            0x017c
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_2_VALUE            0x0180
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_3_VALUE            0x0184
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_4_VALUE            0x0188
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_5_VALUE            0x018c
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_6_VALUE            0x0190
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_7_VALUE            0x0194
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_8_VALUE            0x0198
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_9_VALUE            0x019c
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_10_VALUE           0x01a0
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_11_VALUE           0x01a4
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_12_VALUE           0x01a8
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_13_VALUE           0x01ac
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_14_VALUE           0x01b0
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_15_VALUE           0x01b4
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_0_OVERFLOW         0x01b8
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_1_OVERFLOW         0x01bc
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_2_OVERFLOW         0x01c0
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_3_OVERFLOW         0x01c4
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_4_OVERFLOW         0x01c8
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_5_OVERFLOW         0x01cc
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_6_OVERFLOW         0x01d0
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_7_OVERFLOW         0x01d4
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_8_OVERFLOW         0x01d8
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_9_OVERFLOW         0x01dc
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_10_OVERFLOW        0x01e0
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_11_OVERFLOW        0x01e4
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_12_OVERFLOW        0x01e8
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_13_OVERFLOW        0x01ec
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_14_OVERFLOW        0x01f0
#define  SPAD_BROADCAST_ORLPI_LB_PERFMON_COUNTER_15_OVERFLOW        0x01f4
#define  SPAD_BROADCAST_ORLPI_LB_PRED_WAKEUP_EN                     0x0284
#define  SPAD_BROADCAST_ORLPI_LB_PROF_FILTER_0_CFG                  0x0288
#define  SPAD_BROADCAST_ORLPI_LB_PROF_FILTER_1_CFG                  0x028c
#define  SPAD_BROADCAST_ORLPI_LB_DRP_ECC_ERROR_CFG                  0x1000
#define  SPAD_BROADCAST_ORLPI_LB_DEBUG_CTRL                         0x1008
#define  SPAD_BROADCAST_ORLPI_LB_DRP_ECC_ERROR_INJECTION_0          0x1010
#define  SPAD_BROADCAST_ORLPI_LB_DRP_ECC_ERROR_INJECTION_1          0x1014
#define  SPAD_BROADCAST_ORLPI_LB_DEBUG_TESTBUS                      0x1018
#define  SPAD_BROADCAST_ORLPI_LB_HW_EVENT_CTRL                      0x101c
#define  SPAD_BROADCAST_ORLPI_LB_DRP_INTERRUPT_STATUS               0x1020
#define  SPAD_BROADCAST_ORLPI_LB_DRP_INTERRUPT_ENABLE               0x102c
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_ERROR_STATUS           0x1034
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_SB_ERR_SYN0            0x1038
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_SB_ERR_SYN1            0x103c
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_SB_ERR_SYN2            0x1040
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_SB_ERR_SYN3            0x1044
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_SB_ERR_SYN4            0x1048
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_SB_ERR_SYN5            0x104c
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_SB_ERR_SYN6            0x1050
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_DB_ERR_SYN0            0x1058
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_DB_ERR_SYN1            0x105c
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_DB_ERR_SYN2            0x1060
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_DB_ERR_SYN3            0x1064
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_DB_ERR_SYN4            0x1068
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_DB_ERR_SYN5            0x106c
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_DB_ERR_SYN6            0x1074
#define  SPAD_BROADCAST_ORLPI_LB_DRP_FIFO_EMPTY_STATUS              0x1078
#define  SPAD_BROADCAST_ORLPI_LB_DRP_FIFO_FULL_STATUS               0x107c
#define  SPAD_BROADCAST_ORLPI_LB_ADDR_DECODE_ERR_CFG                0x1080
#define  SPAD_BROADCAST_ORLPI_LB_ADDR_DECODE_ERR_INTERRUPT_STATUS   0x1084
#define  SPAD_BROADCAST_ORLPI_LB_ADDR_DECODE_ERR_INTERRUPT_ENABLE   0x108c
#define  SPAD_BROADCAST_ORLPI_LB_RD_ADDR_DECODE_ERR_STATUS1         0x1090
#define  SPAD_BROADCAST_ORLPI_LB_RD_ADDR_DECODE_ERR_STATUS2         0x1094
#define  SPAD_BROADCAST_ORLPI_LB_RD_ADDR_DECODE_ERR_STATUS3         0x1098
#define  SPAD_BROADCAST_ORLPI_LB_RD_ADDR_DECODE_ERR_STATUS4         0x109c
#define  SPAD_BROADCAST_ORLPI_LB_RD_ADDR_DECODE_ERR_STATUS5         0x10a0
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_SB_ERR_SYN7            0x10a4
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_SB_ERR_SYN8            0x10a8
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_SB_ERR_SYN9            0x10ac
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_ERROR_STATUS           0x10b0
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_SB_ERR_SYN10           0x10b4
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_SB_ERR_SYN7            0x10b8
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_SB_ERR_SYN8            0x10bc
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_SB_ERR_SYN9            0x10c0
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_SB_ERR_SYN10           0x10c4
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_DB_ERR_SYN7            0x10c8
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_DB_ERR_SYN8            0x10cc
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_DB_ERR_SYN9            0x10d0
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_DB_ERR_SYN10           0x10d4
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_DB_ERR_SYN7            0x10d8
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_DB_ERR_SYN8            0x10dc
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_DB_ERR_SYN9            0x10e0
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH0_ECC_DB_ERR_SYN10           0x10e4
#define  SPAD_BROADCAST_ORLPI_LB_WR_ADDR_DECODE_ERR_STATUS1         0x10e8
#define  SPAD_BROADCAST_ORLPI_LB_WR_ADDR_DECODE_ERR_STATUS2         0x10ec
#define  SPAD_BROADCAST_ORLPI_LB_WR_ADDR_DECODE_ERR_STATUS3         0x10f0
#define  SPAD_BROADCAST_ORLPI_LB_WR_ADDR_DECODE_ERR_STATUS4         0x10f4
#define  SPAD_BROADCAST_ORLPI_LB_WR_ADDR_DECODE_ERR_STATUS5         0x10f8
#define  SPAD_BROADCAST_ORLPI_LB_DCRSW_CFG                          0x1110
#define  SPAD_BROADCAST_ORLPI_LB_DCRSW_STATUS0                      0x1114
#define  SPAD_BROADCAST_ORLPI_LB_DCRSW_STATUS1                      0x1118
#define  SPAD_BROADCAST_ORLPI_LB_DCRSW_STATUS2                      0x111c
#define  SPAD_BROADCAST_ORLPI_LB_DCRSW_STATUS3                      0x1120
#define  SPAD_BROADCAST_ORLPI_LB_DCRSW_STATUS4                      0x1124
#define  SPAD_BROADCAST_ORLPI_LB_DCRSW_STATUS5                      0x1128
#define  SPAD_BROADCAST_ORLPI_LB_DCRSW_STATUS6                      0x112c
#define  SPAD_BROADCAST_ORLPI_LB_DCRSW_STATUS7                      0x1130
#define  SPAD_BROADCAST_ORLPI_LB_DCRSW_STATUS8                      0x1134
#define  SPAD_BROADCAST_ORLPI_LB_IF_CHANNEL_STATUS                  0x1138
#define  SPAD_BROADCAST_ORLPI_LB_FIFO_STATUS                        0x113c
#define  SPAD_BROADCAST_ORLPI_LB_RSPPROC_CREDITS_STATUS             0x1140
#define  SPAD_BROADCAST_ORLPI_LB_DBG_EVENT_STATUS                   0x118c
#define  SPAD_BROADCAST_ORLPI_LB_DBG_EVENT_FWD                      0x1194
#define  SPAD_BROADCAST_ORLPI_LB_UNS_ERR_CFG                        0x1200
#define  SPAD_BROADCAST_ORLPI_LB_UNS_ERR_STATUS1                    0x1204
#define  SPAD_BROADCAST_ORLPI_LB_UNS_ERR_STATUS2                    0x1208
#define  SPAD_BROADCAST_ORLPI_LB_UNS_ERR_STATUS3                    0x120c
#define  SPAD_BROADCAST_ORLPI_LB_UNS_ERR_STATUS4                    0x1210
#define  SPAD_BROADCAST_ORLPI_LB_UNS_ERR_STATUS5                    0x1214
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_SB_ERR_SYN0            0x1218
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_SB_ERR_SYN1            0x121c
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_SB_ERR_SYN2            0x1220
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_SB_ERR_SYN3            0x1224
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_SB_ERR_SYN4            0x1228
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_SB_ERR_SYN5            0x122c
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_SB_ERR_SYN6            0x1230
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_DB_ERR_SYN0            0x1238
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_DB_ERR_SYN1            0x123c
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_DB_ERR_SYN2            0x1240
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_DB_ERR_SYN3            0x1244
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_DB_ERR_SYN4            0x1248
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_DB_ERR_SYN5            0x124c
#define  SPAD_BROADCAST_ORLPI_LB_DRP_CH1_ECC_DB_ERR_SYN6            0x1250
#define  SPAD_BROADCAST_ORLPI_LB_FF_CLK_ON_CTRL                     0x1254
#define  SPAD_BROADCAST_ORLPI_LB_BIST_CTRL                          0x2000
#define  SPAD_BROADCAST_ORLPI_LB_BIST_CLK_CTRL                      0x2008
#define  SPAD_BROADCAST_ORLPI_LB_BIST_WRITE_CONFIG1                 0x2010
#define  SPAD_BROADCAST_ORLPI_LB_BIST_WRITE_CONFIG2                 0x2014
#define  SPAD_BROADCAST_ORLPI_LB_BIST_WR_ADDR                       0x2018
#define  SPAD_BROADCAST_ORLPI_LB_BIST_WR_BIST_SEED_31_0             0x201c
#define  SPAD_BROADCAST_ORLPI_LB_BIST_WR_BIST_SEED_63_32            0x2020
#define  SPAD_BROADCAST_ORLPI_LB_BIST_WR_BIST_SEED_95_64            0x2024
#define  SPAD_BROADCAST_ORLPI_LB_BIST_WR_BIST_SEED_127_96           0x202c
#define  SPAD_BROADCAST_ORLPI_LB_BIST_READ_CONFIG1                  0x2040
#define  SPAD_BROADCAST_ORLPI_LB_BIST_READ_CONFIG2                  0x2044
#define  SPAD_BROADCAST_ORLPI_LB_BIST_RD_ADDR                       0x2048
#define  SPAD_BROADCAST_ORLPI_LB_BIST_RD_BIST_SEED_31_0             0x204c
#define  SPAD_BROADCAST_ORLPI_LB_BIST_RD_BIST_SEED_63_32            0x2050
#define  SPAD_BROADCAST_ORLPI_LB_BIST_RD_BIST_SEED_95_64            0x2054
#define  SPAD_BROADCAST_ORLPI_LB_BIST_RD_BIST_SEED_127_96           0x2058
#define  SPAD_BROADCAST_ORLPI_LB_BIST_LFSR_TAP_POINT                0x206c
#define  SPAD_BROADCAST_ORLPI_LB_BIST_STATUS                        0x2070
#define  SPAD_BROADCAST_ORLPI_LB_BIST_FAILURE                       0x2074
#define  SPAD_BROADCAST_ORLPI_LB_BIST_FAILURE_0_BITS                0x2078
#define  SPAD_BROADCAST_ORLPI_LB_BIST_FAILURE_1_BITS                0x207c
#define  SPAD_BROADCAST_ORLPI_LB_BIST_FAILURE_2_BITS                0x2080
#define  SPAD_BROADCAST_ORLPI_LB_BIST_FAILURE_3_BITS                0x2084
#define  SPAD_BROADCAST_ORLPI_LB_BIST_FAILURE_4_BITS                0x2088
#define  SPAD_BROADCAST_ORLPI_LB_BIST_FAILURE_5_BITS                0x208c
#define  SPAD_BROADCAST_ORLPI_LB_BIST_SPARE                         0x20a0
#define  SPAD_BROADCAST_ORLPI_LB_BIST_TAG_RAM_EXTRA_COL_ACT         0x20a4

#define SPAD_BROADCAST_ANDLPI_LB_RAM_TIMING0                        0x0000
#define SPAD_BROADCAST_ANDLPI_LB_RAM_TIMING1                        0x0004
#define SPAD_BROADCAST_ANDLPI_LB_RAM_TIMING2                        0x0008
#define SPAD_BROADCAST_ANDLPI_LB_PCB_SLP_SEL0                       0x000c
#define SPAD_BROADCAST_ANDLPI_LB_PCB_SLP_NRET_SEL0                  0x0010
#define SPAD_BROADCAST_ANDLPI_LB_PCB_SLP_SEL1                       0x0014
#define SPAD_BROADCAST_ANDLPI_LB_PCB_SLP_NRET_SEL1                  0x0018
#define SPAD_BROADCAST_ANDLPI_LB_PCB_WAKEUP_SEL0                    0x001c
#define SPAD_BROADCAST_ANDLPI_LB_PCB_WAKEUP_SEL1                    0x0020
#define SPAD_BROADCAST_ANDLPI_LB_PCB_ENABLE                         0x0034
#define SPAD_BROADCAST_ANDLPI_LB_RAM_IDLE_THRESHOLD                 0x0044
#define SPAD_BROADCAST_ANDLPI_LB_PCB_CMD                            0x0048
#define SPAD_BROADCAST_ANDLPI_LB_COUNTER_SYNC_RATE                  0x004c
#define SPAD_BROADCAST_ANDLPI_LB_RAMSLP_STATUS                      0x0050
#define SPAD_BROADCAST_ANDLPI_LB_PCB_PWR_STATUS0                    0x0054
#define SPAD_BROADCAST_ANDLPI_LB_PCB_PWR_STATUS1                    0x0058
#define SPAD_BROADCAST_ANDLPI_LB_PCB_PWR_STATUS2                    0x005c
#define SPAD_BROADCAST_ANDLPI_LB_PCB_PWR_STATUS3                    0x0060
#define SPAD_BROADCAST_ANDLPI_LB_PRE_ARES_STATUS                    0x0064
#define SPAD_BROADCAST_ANDLPI_LB_DEBUG_CTRL0                        0x0068
#define SPAD_BROADCAST_ANDLPI_LB_DEBUG_CTRL1                        0x006c
#define SPAD_BROADCAST_ANDLPI_LB_DEBUG_CTRL2                        0x0070
#define SPAD_BROADCAST_ANDLPI_LB_DEBUG_CTRL3                        0x0074
#define SPAD_BROADCAST_ANDLPI_LB_DEBUG_CTRL4                        0x0078
#define SPAD_BROADCAST_ANDLPI_LB_DEBUG_CTRL5                        0x007c
#define SPAD_BROADCAST_ANDLPI_LB_PCBSLP_STATUS0                     0x0080
#define SPAD_BROADCAST_ANDLPI_LB_PCBSLP_STATUS1                     0x0084
#define SPAD_BROADCAST_ANDLPI_LB_PCBSLP_STATUS2                     0x0088
#define SPAD_BROADCAST_ANDLPI_LB_PCBSLP_STATUS3                     0x008c
#define SPAD_BROADCAST_ANDLPI_LB_PCBSLP_STATUS4                     0x0090
#define SPAD_BROADCAST_ANDLPI_LB_PCBSLP_STATUS5                     0x0094
#define SPAD_BROADCAST_ANDLPI_LB_PCBSLP_STATUS6                     0x0098
#define SPAD_BROADCAST_ANDLPI_LB_CLK_EN_CFG                         0x0104
#define SPAD_BROADCAST_ANDLPI_LB_PRE_ARES_CTRL                      0x0108
#define SPAD_BROADCAST_ANDLPI_LB_ADDR_REGION_CFG0                   0x0110
#define SPAD_BROADCAST_ANDLPI_LB_ADDR_REGION_CFG1                   0x0114
#define SPAD_BROADCAST_ANDLPI_LB_ADDR_REGION_CFG2                   0x0118
#define SPAD_BROADCAST_ANDLPI_LB_ADDR_REGION_CFG3                   0x011c
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_MODE                       0x0120
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_CORE_CLOCK_CTRL            0x0124
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_CFG_CLOCK_CTRL             0x0128
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_DEBUG_CTRL                 0x012c
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_STATUS                     0x0130
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_CONFIGURATION_INFO         0x0134
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_0_CONFIG           0x0138
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_1_CONFIG           0x013c
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_2_CONFIG           0x0140
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_3_CONFIG           0x0144
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_4_CONFIG           0x0148
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_5_CONFIG           0x014c
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_6_CONFIG           0x0150
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_7_CONFIG           0x0154
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_8_CONFIG           0x0158
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_9_CONFIG           0x015c
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_10_CONFIG          0x0160
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_11_CONFIG          0x0164
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_12_CONFIG          0x0168
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_13_CONFIG          0x016c
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_14_CONFIG          0x0170
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_15_CONFIG          0x0174
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_0_VALUE            0x0178
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_1_VALUE            0x017c
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_2_VALUE            0x0180
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_3_VALUE            0x0184
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_4_VALUE            0x0188
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_5_VALUE            0x018c
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_6_VALUE            0x0190
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_7_VALUE            0x0194
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_8_VALUE            0x0198
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_9_VALUE            0x019c
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_10_VALUE           0x01a0
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_11_VALUE           0x01a4
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_12_VALUE           0x01a8
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_13_VALUE           0x01ac
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_14_VALUE           0x01b0
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_15_VALUE           0x01b4
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_0_OVERFLOW         0x01b8
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_1_OVERFLOW         0x01bc
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_2_OVERFLOW         0x01c0
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_3_OVERFLOW         0x01c4
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_4_OVERFLOW         0x01c8
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_5_OVERFLOW         0x01cc
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_6_OVERFLOW         0x01d0
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_7_OVERFLOW         0x01d4
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_8_OVERFLOW         0x01d8
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_9_OVERFLOW         0x01dc
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_10_OVERFLOW        0x01e0
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_11_OVERFLOW        0x01e4
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_12_OVERFLOW        0x01e8
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_13_OVERFLOW        0x01ec
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_14_OVERFLOW        0x01f0
#define SPAD_BROADCAST_ANDLPI_LB_PERFMON_COUNTER_15_OVERFLOW        0x01f4
#define SPAD_BROADCAST_ANDLPI_LB_PRED_WAKEUP_EN                     0x0284
#define SPAD_BROADCAST_ANDLPI_LB_PROF_FILTER_0_CFG                  0x0288
#define SPAD_BROADCAST_ANDLPI_LB_PROF_FILTER_1_CFG                  0x028c
#define SPAD_BROADCAST_ANDLPI_LB_DRP_ECC_ERROR_CFG                  0x1000
#define SPAD_BROADCAST_ANDLPI_LB_DEBUG_CTRL                         0x1008
#define SPAD_BROADCAST_ANDLPI_LB_DRP_ECC_ERROR_INJECTION_0          0x1010
#define SPAD_BROADCAST_ANDLPI_LB_DRP_ECC_ERROR_INJECTION_1          0x1014
#define SPAD_BROADCAST_ANDLPI_LB_DEBUG_TESTBUS                      0x1018
#define SPAD_BROADCAST_ANDLPI_LB_HW_EVENT_CTRL                      0x101c
#define SPAD_BROADCAST_ANDLPI_LB_DRP_INTERRUPT_STATUS               0x1020
#define SPAD_BROADCAST_ANDLPI_LB_DRP_INTERRUPT_ENABLE               0x102c
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_ERROR_STATUS           0x1034
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_SB_ERR_SYN0            0x1038
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_SB_ERR_SYN1            0x103c
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_SB_ERR_SYN2            0x1040
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_SB_ERR_SYN3            0x1044
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_SB_ERR_SYN4            0x1048
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_SB_ERR_SYN5            0x104c
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_SB_ERR_SYN6            0x1050
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_DB_ERR_SYN0            0x1058
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_DB_ERR_SYN1            0x105c
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_DB_ERR_SYN2            0x1060
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_DB_ERR_SYN3            0x1064
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_DB_ERR_SYN4            0x1068
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_DB_ERR_SYN5            0x106c
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_DB_ERR_SYN6            0x1074
#define SPAD_BROADCAST_ANDLPI_LB_DRP_FIFO_EMPTY_STATUS              0x1078
#define SPAD_BROADCAST_ANDLPI_LB_DRP_FIFO_FULL_STATUS               0x107c
#define SPAD_BROADCAST_ANDLPI_LB_ADDR_DECODE_ERR_CFG                0x1080
#define SPAD_BROADCAST_ANDLPI_LB_ADDR_DECODE_ERR_INTERRUPT_STATUS   0x1084
#define SPAD_BROADCAST_ANDLPI_LB_ADDR_DECODE_ERR_INTERRUPT_ENABLE   0x108c
#define SPAD_BROADCAST_ANDLPI_LB_RD_ADDR_DECODE_ERR_STATUS1         0x1090
#define SPAD_BROADCAST_ANDLPI_LB_RD_ADDR_DECODE_ERR_STATUS2         0x1094
#define SPAD_BROADCAST_ANDLPI_LB_RD_ADDR_DECODE_ERR_STATUS3         0x1098
#define SPAD_BROADCAST_ANDLPI_LB_RD_ADDR_DECODE_ERR_STATUS4         0x109c
#define SPAD_BROADCAST_ANDLPI_LB_RD_ADDR_DECODE_ERR_STATUS5         0x10a0
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_SB_ERR_SYN7            0x10a4
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_SB_ERR_SYN8            0x10a8
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_SB_ERR_SYN9            0x10ac
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_ERROR_STATUS           0x10b0
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_SB_ERR_SYN10           0x10b4
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_SB_ERR_SYN7            0x10b8
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_SB_ERR_SYN8            0x10bc
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_SB_ERR_SYN9            0x10c0
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_SB_ERR_SYN10           0x10c4
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_DB_ERR_SYN7            0x10c8
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_DB_ERR_SYN8            0x10cc
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_DB_ERR_SYN9            0x10d0
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_DB_ERR_SYN10           0x10d4
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_DB_ERR_SYN7            0x10d8
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_DB_ERR_SYN8            0x10dc
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_DB_ERR_SYN9            0x10e0
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH0_ECC_DB_ERR_SYN10           0x10e4
#define SPAD_BROADCAST_ANDLPI_LB_WR_ADDR_DECODE_ERR_STATUS1         0x10e8
#define SPAD_BROADCAST_ANDLPI_LB_WR_ADDR_DECODE_ERR_STATUS2         0x10ec
#define SPAD_BROADCAST_ANDLPI_LB_WR_ADDR_DECODE_ERR_STATUS3         0x10f0
#define SPAD_BROADCAST_ANDLPI_LB_WR_ADDR_DECODE_ERR_STATUS4         0x10f4
#define SPAD_BROADCAST_ANDLPI_LB_WR_ADDR_DECODE_ERR_STATUS5         0x10f8
#define SPAD_BROADCAST_ANDLPI_LB_DCRSW_CFG                          0x1110
#define SPAD_BROADCAST_ANDLPI_LB_DCRSW_STATUS0                      0x1114
#define SPAD_BROADCAST_ANDLPI_LB_DCRSW_STATUS1                      0x1118
#define SPAD_BROADCAST_ANDLPI_LB_DCRSW_STATUS2                      0x111c
#define SPAD_BROADCAST_ANDLPI_LB_DCRSW_STATUS3                      0x1120
#define SPAD_BROADCAST_ANDLPI_LB_DCRSW_STATUS4                      0x1124
#define SPAD_BROADCAST_ANDLPI_LB_DCRSW_STATUS5                      0x1128
#define SPAD_BROADCAST_ANDLPI_LB_DCRSW_STATUS6                      0x112c
#define SPAD_BROADCAST_ANDLPI_LB_DCRSW_STATUS7                      0x1130
#define SPAD_BROADCAST_ANDLPI_LB_DCRSW_STATUS8                      0x1134
#define SPAD_BROADCAST_ANDLPI_LB_IF_CHANNEL_STATUS                  0x1138
#define SPAD_BROADCAST_ANDLPI_LB_FIFO_STATUS                        0x113c
#define SPAD_BROADCAST_ANDLPI_LB_RSPPROC_CREDITS_STATUS             0x1140
#define SPAD_BROADCAST_ANDLPI_LB_DBG_EVENT_STATUS                   0x118c
#define SPAD_BROADCAST_ANDLPI_LB_DBG_EVENT_FWD                      0x1194
#define SPAD_BROADCAST_ANDLPI_LB_UNS_ERR_CFG                        0x1200
#define SPAD_BROADCAST_ANDLPI_LB_UNS_ERR_STATUS1                    0x1204
#define SPAD_BROADCAST_ANDLPI_LB_UNS_ERR_STATUS2                    0x1208
#define SPAD_BROADCAST_ANDLPI_LB_UNS_ERR_STATUS3                    0x120c
#define SPAD_BROADCAST_ANDLPI_LB_UNS_ERR_STATUS4                    0x1210
#define SPAD_BROADCAST_ANDLPI_LB_UNS_ERR_STATUS5                    0x1214
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_SB_ERR_SYN0            0x1218
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_SB_ERR_SYN1            0x121c
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_SB_ERR_SYN2            0x1220
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_SB_ERR_SYN3            0x1224
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_SB_ERR_SYN4            0x1228
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_SB_ERR_SYN5            0x122c
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_SB_ERR_SYN6            0x1230
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_DB_ERR_SYN0            0x1238
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_DB_ERR_SYN1            0x123c
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_DB_ERR_SYN2            0x1240
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_DB_ERR_SYN3            0x1244
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_DB_ERR_SYN4            0x1248
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_DB_ERR_SYN5            0x124c
#define SPAD_BROADCAST_ANDLPI_LB_DRP_CH1_ECC_DB_ERR_SYN6            0x1250
#define SPAD_BROADCAST_ANDLPI_LB_FF_CLK_ON_CTRL                     0x1254
#define SPAD_BROADCAST_ANDLPI_LB_BIST_CTRL                          0x2000
#define SPAD_BROADCAST_ANDLPI_LB_BIST_CLK_CTRL                      0x2008
#define SPAD_BROADCAST_ANDLPI_LB_BIST_WRITE_CONFIG1                 0x2010
#define SPAD_BROADCAST_ANDLPI_LB_BIST_WRITE_CONFIG2                 0x2014
#define SPAD_BROADCAST_ANDLPI_LB_BIST_WR_ADDR                       0x2018
#define SPAD_BROADCAST_ANDLPI_LB_BIST_WR_BIST_SEED_31_0             0x201c
#define SPAD_BROADCAST_ANDLPI_LB_BIST_WR_BIST_SEED_63_32            0x2020
#define SPAD_BROADCAST_ANDLPI_LB_BIST_WR_BIST_SEED_95_64            0x2024
#define SPAD_BROADCAST_ANDLPI_LB_BIST_WR_BIST_SEED_127_96           0x202c
#define SPAD_BROADCAST_ANDLPI_LB_BIST_READ_CONFIG1                  0x2040
#define SPAD_BROADCAST_ANDLPI_LB_BIST_READ_CONFIG2                  0x2044
#define SPAD_BROADCAST_ANDLPI_LB_BIST_RD_ADDR                       0x2048
#define SPAD_BROADCAST_ANDLPI_LB_BIST_RD_BIST_SEED_31_0             0x204c
#define SPAD_BROADCAST_ANDLPI_LB_BIST_RD_BIST_SEED_63_32            0x2050
#define SPAD_BROADCAST_ANDLPI_LB_BIST_RD_BIST_SEED_95_64            0x2054
#define SPAD_BROADCAST_ANDLPI_LB_BIST_RD_BIST_SEED_127_96           0x2058
#define SPAD_BROADCAST_ANDLPI_LB_BIST_LFSR_TAP_POINT                0x206c
#define SPAD_BROADCAST_ANDLPI_LB_BIST_STATUS                        0x2070
#define SPAD_BROADCAST_ANDLPI_LB_BIST_FAILURE                       0x2074
#define SPAD_BROADCAST_ANDLPI_LB_BIST_FAILURE_0_BITS                0x2078
#define SPAD_BROADCAST_ANDLPI_LB_BIST_FAILURE_1_BITS                0x207c
#define SPAD_BROADCAST_ANDLPI_LB_BIST_FAILURE_2_BITS                0x2080
#define SPAD_BROADCAST_ANDLPI_LB_BIST_FAILURE_3_BITS                0x2084
#define SPAD_BROADCAST_ANDLPI_LB_BIST_FAILURE_4_BITS                0x2088
#define SPAD_BROADCAST_ANDLPI_LB_BIST_FAILURE_5_BITS                0x208c
#define SPAD_BROADCAST_ANDLPI_LB_BIST_SPARE                         0x20a0
#define SPAD_BROADCAST_ANDLPI_LB_BIST_TAG_RAM_EXTRA_COL_ACT         0x20a4
#endif
